### ISSUE TITLE
在代码执行到 Cv2.FindContoursAsArray 时报错了

### ISSUE THREAD

**Issue by carlding1990** [yangzhongke/Zack.OpenCVSharp.Ext#2]
在代码执行到 Cv2.FindContoursAsArray(matMask, RetrievalModes.External, ContourApproximationModes.ApproxNone) 时候报错了，这个要怎么处理呢？
System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”

**Comment by yangzhongke** [comment]
如果我的代码没有动就出这个异常的话，我就不清楚了。
